services:
  gripl-frontend:
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://gripl-backend:8080}
    networks:
      - app
    ports:
      - "${FRONTEND_PORT:-3000}:3000"

  gripl-backend:
    env_file:
      - .env.local
    environment:
      - FRONTEND_BASE_URL=http://localhost
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gripl-postgres:5432/${POSTGRES_DB:-gripldb}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    networks:
      - app
    ports:
      - "${BACKEND_PORT:-8080}:8080"

  gripl-postgres:
    env_file:
      - .env.local
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

networks:
  app:
    external: false
