package de.mertendieckmann.griplbackend.adapter.web

import de.mertendieckmann.griplbackend.model.dto.CreateDatasetRequest
import de.mertendieckmann.griplbackend.model.dto.Dataset
import de.mertendieckmann.griplbackend.repository.DatasetRepository
import de.mertendieckmann.griplbackend.security.authenticatedUserId
import de.mertendieckmann.griplbackend.security.requirePrivilegedGriplRole
import io.swagger.v3.oas.annotations.Operation
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import org.springframework.web.server.ServerWebExchange

@RestController
@RequestMapping("/dataset")
class DatasetController(
    private val datasetRepository: DatasetRepository
) {
    @Operation(
        summary = "Create a new Dataset",
        description = "Creates a new empty dataset entry owned by the authenticated user. " +
            "The Id will be automatically generated by the database and returned."
    )
    @PostMapping("", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun createDataset(
        @RequestBody request: CreateDatasetRequest,
        exchange: ServerWebExchange
    ): ResponseEntity<Int> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        val idOfCreatedDataset = datasetRepository.createDataset(request, userId)
        return if (idOfCreatedDataset > 0) {
            ResponseEntity.status(HttpStatus.CREATED).body(idOfCreatedDataset)
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(-1)
        }
    }

    @Operation(
        summary = "Get all Datasets",
        description = "Returns all datasets owned by the authenticated user."
    )
    @GetMapping("", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getAllDatasets(exchange: ServerWebExchange): List<Dataset> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        return datasetRepository.getDatasetsByOwner(userId)
    }

    @Operation(
        summary = "Delete Dataset",
        description = "Deletes a dataset owned by the authenticated user and detaches its test cases. " +
            "Returns 404 if the dataset does not exist or is not owned by the caller."
    )
    @DeleteMapping("/{datasetId}")
    fun deleteDataset(
        @PathVariable("datasetId") datasetId: Long,
        exchange: ServerWebExchange
    ): ResponseEntity<String> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        if (datasetRepository.getDatasetByIdAndOwner(datasetId, userId) == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("No dataset found for Id: $datasetId")
        }
        val affectedRows = datasetRepository.deleteDataset(datasetId, userId)
        return if (affectedRows > 0) {
            ResponseEntity.ok("Dataset deleted successfully")
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to delete dataset")
        }
    }
}
