package de.mertendieckmann.griplbackend.adapter.web

import de.mertendieckmann.griplbackend.application.PreviewGenerator
import de.mertendieckmann.griplbackend.model.dto.*
import de.mertendieckmann.griplbackend.repository.DatasetRepository
import de.mertendieckmann.griplbackend.repository.EvaluationDataRepository
import de.mertendieckmann.griplbackend.repository.PreviewCacheRepository
import de.mertendieckmann.griplbackend.security.authenticatedUserId
import de.mertendieckmann.griplbackend.security.requirePrivilegedGriplRole
import io.github.oshai.kotlinlogging.KotlinLogging
import io.swagger.v3.oas.annotations.Operation
import org.springframework.core.io.buffer.DataBufferUtils
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.http.codec.multipart.FilePart
import org.springframework.http.server.reactive.ServerHttpRequest
import org.springframework.web.bind.annotation.*
import org.springframework.web.server.ResponseStatusException
import org.springframework.web.server.ServerWebExchange
import reactor.core.publisher.Mono
import reactor.core.scheduler.Schedulers

@RestController
@RequestMapping("/dataset/testcase")
class EvaluationDataController(
    private val evaluationDataRepository: EvaluationDataRepository,
    private val datasetRepository: DatasetRepository,
    private val previewCacheRepository: PreviewCacheRepository,
    private val previewGenerator: PreviewGenerator
) {
    private val log = KotlinLogging.logger { }

    // GRIPL-v2#33: every endpoint below is scoped to the authenticated user via
    // the test case's parent dataset. A test case must belong to a dataset the
    // caller owns; anything else is a 404 (existence is not leaked) or, for a
    // create without a dataset, a 400.
    // GRIPL-v2#40: the whole "Labeling" surface (this controller) is admin/
    // researcher only — dpo and end-user only get the sandbox.

    @Operation(
        summary = "Get all Testcases Metadata",
        description = "Returns the metadata of the caller's test cases (those whose parent dataset they own). " +
            "Optionally filtered to a single dataset via the datasetId query parameter."
    )
    @GetMapping("", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getAllBpmnDatasetMeta(
        @RequestParam(required = false) datasetId: Int? = null,
        exchange: ServerWebExchange
    ): List<EvaluationDataMeta> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        val datasets = evaluationDataRepository.getEvaluationDataForOwner(userId, datasetId)
        return datasets.map { EvaluationDataMeta(it.id, it.name, it.datasetId) }
    }

    @Operation(
        summary = "Insert a new Testcase",
        description = "Inserts a new test case into a dataset owned by the caller. The datasetId is required and " +
            "must reference a dataset the caller owns. The Id is generated by the database and returned."
    )
    @PostMapping(
        "",
        consumes = [MediaType.MULTIPART_FORM_DATA_VALUE],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun insertBpmnDataset(
        @RequestPart("name") name: String? = null,
        @RequestPart("bpmnFile") bpmnFile: FilePart,
        @RequestPart("expectedValues") expectedValues: List<ExpectedValue>,
        @RequestPart("datasetId") datasetId: String? = null,
        exchange: ServerWebExchange
    ): Mono<ResponseEntity<Int>> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        val parentDatasetId = datasetId?.toLongOrNull()
            ?: throw ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "A test case must be created inside a dataset (datasetId is required)."
            )
        if (!datasetRepository.isDatasetOwnedBy(parentDatasetId, userId)) {
            throw ResponseStatusException(HttpStatus.NOT_FOUND, "No dataset found for Id: $parentDatasetId")
        }

        val bpmnXmlMono: Mono<String> = DataBufferUtils
            .join(bpmnFile.content())
            .map { dataBuffer ->
                dataBuffer.asInputStream().bufferedReader().use { it.readText() }
            }

        return bpmnXmlMono.flatMap { bpmnXml ->
            val evaluationData = EvaluationDataWithOptionalId(
                name = name,
                bpmnXml = bpmnXml,
                expectedValues = expectedValues,
                datasetId = parentDatasetId
            )

            val idOfCreatedEntry = evaluationDataRepository.insertEvaluationData(evaluationData)

            if (idOfCreatedEntry != null) {
                Mono.just(ResponseEntity.status(HttpStatus.CREATED).body(idOfCreatedEntry))
            } else {
                Mono.just(ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(-1))
            }
        }
    }

    @Operation(
        summary = "Get Testcase by Id",
        description = "Returns the full test case entry for a specific Id, if the caller owns its parent dataset."
    )
    @GetMapping("/{id}", produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getBpmnDataset(@PathVariable("id") id: Long, exchange: ServerWebExchange): EvaluationData {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        return evaluationDataRepository.getEvaluationDataByIdForOwner(id, userId)
            ?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "No dataset entry found for Id: $id")
    }

    @Operation(
        summary = "Update Testcase by Id",
        description = "Updates an existing test case, if the caller owns its parent dataset."
    )
    @PostMapping(
        "/{id}",
        consumes = [MediaType.MULTIPART_FORM_DATA_VALUE],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun updateBpmnDataset(
        @PathVariable("id") id: Long,
        @RequestPart("name") name: String? = null,
        @RequestPart("bpmnFile") bpmnFile: FilePart,
        @RequestPart("expectedValues") expectedValues: List<ExpectedValue>,
        exchange: ServerWebExchange
    ): Mono<ResponseEntity<String>> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        val existingEntry = evaluationDataRepository.getEvaluationDataByIdForOwner(id, userId)
            ?: return Mono.just(ResponseEntity.status(HttpStatus.NOT_FOUND).body("No dataset entry found for Id: $id"))

        log.info { "Updating existing dataset entry with Id: $id" }

        val bpmnXmlMomo: Mono<String> = DataBufferUtils
            .join(bpmnFile.content())
            .map { dataBuffer ->
                dataBuffer.asInputStream().bufferedReader().use { it.readText() }
            }

        return bpmnXmlMomo.flatMap { bpmnXml ->
            val affectedRows = evaluationDataRepository.updateEvaluationData(
                EvaluationData(
                    id = existingEntry.id,
                    name = name,
                    bpmnXml = bpmnXml,
                    expectedValues = expectedValues
                ),
                userId
            )

            if (affectedRows > 0) {
                Mono.just(ResponseEntity.ok("Dataset entry updated successfully"))
            } else {
                Mono.just(ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to update dataset entry"))
            }
        }
    }

    @Operation(
        summary = "Delete Testcase by Id",
        description = "Deletes a test case, if the caller owns its parent dataset."
    )
    @DeleteMapping("/{id}")
    fun deleteBpmnDataset(@PathVariable("id") id: Long, exchange: ServerWebExchange): ResponseEntity<String> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()
        if (evaluationDataRepository.getEvaluationDataByIdForOwner(id, userId) == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("No dataset entry found for Id: $id")
        }

        log.info { "Deleting dataset entry with Id: $id" }

        val affectedRows = evaluationDataRepository.deleteEvaluationData(id, userId)
        return if (affectedRows > 0) {
            ResponseEntity.ok("Dataset entry deleted successfully")
        } else {
            ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to delete dataset entry")
        }
    }

    @Operation(
        summary = "Get SVG Preview of Testcase",
        description = "Generates a SVG preview of the process model for a test case the caller owns."
    )
    @GetMapping("/{id}/preview", produces = ["image/svg+xml"])
    fun getSvg(
        @PathVariable id: Long,
        @RequestParam correctIds: List<String> = emptyList(),
        @RequestParam falsePositiveIds: List<String> = emptyList(),
        @RequestParam falseNegativeIds: List<String> = emptyList(),
        @RequestParam theme: String = "light",
        request: ServerHttpRequest,
        exchange: ServerWebExchange
    ): Mono<ResponseEntity<String>> {
        val userId = exchange.authenticatedUserId()
        exchange.requirePrivilegedGriplRole()

        val requestPath = request.uri.path
        val requestQueryWithoutSalt = request.uri.query
            ?.replace(Regex("&salt=[^&]*"), "")
            ?.let { "?$it" }.orEmpty()
        val relativeRequestUrl = "$requestPath$requestQueryWithoutSalt"

        // Preview rendering (Playwright/Chromium) and the repository lookups below are all
        // blocking, so they must run off the Netty event-loop thread.
        return Mono.fromCallable {
            renderSvgPreview(id, userId, relativeRequestUrl, correctIds, falsePositiveIds, falseNegativeIds, theme)
        }.subscribeOn(Schedulers.boundedElastic())
    }

    private fun renderSvgPreview(
        id: Long,
        userId: String,
        relativeRequestUrl: String,
        correctIds: List<String>,
        falsePositiveIds: List<String>,
        falseNegativeIds: List<String>,
        theme: String
    ): ResponseEntity<String> {
        // Ownership check first — before any cache hit can short-circuit it.
        val datasetEntry = evaluationDataRepository.getEvaluationDataByIdForOwner(id, userId)
            ?: return ResponseEntity.status(HttpStatus.NOT_FOUND).body("Kein Datensatz gefunden für Id: $id")

        val cachedPreview = previewCacheRepository.getCachedPreview(id, relativeRequestUrl)
        if (cachedPreview != null) {
            log.info { "Returning cached SVG preview for Id: $id" }
            return ResponseEntity.ok()
                .header("Content-Type", "image/svg+xml")
                .body(cachedPreview.svg)
        }

        val bpmnXml = datasetEntry.bpmnXml

        val svg = try {
            previewGenerator.convertXmlToSvg(bpmnXml, correctIds = correctIds, falsePositiveIds = falsePositiveIds, falseNegativeIds = falseNegativeIds, theme = theme)
        } catch (ex: IllegalArgumentException) {
            log.error(ex) { "Ungültiges BPMN XML für Id: $id" }
            return ResponseEntity.badRequest().body("Fehler beim Parsen: ${ex.message}")
        } catch (ex: Exception) {
            log.error(ex) { "Fehler beim Generieren des SVG für Id: $id" }
            return ResponseEntity.status(500).body("Serverfehler: ${ex.message}")
        }

        previewCacheRepository.insertPreviewCache(PreviewCacheInsert(
            evaluationDataId = id,
            urlCacheKey = relativeRequestUrl,
            svg = svg
        ))

        return ResponseEntity.ok()
            .header("Content-Type", "image/svg+xml")
            .body(svg)
    }
}
